### ISSUE TITLE
Learn Go and practice using the Spotify API

### ISSUE THREAD

**Issue by ddusichka** [GenerateNU/platnm#10]
# Resources
**Go**
The following are different types of tutorials (video, interactive, article-based) - poke around and see which one works best for you. You don't have to read them all! (pls don't)

* Interactive tour from Go itself: https://go.dev/tour/welcome/1
* Intro video: https://www.youtube.com/watch?v=8uiZC0l4Ajw
* Go by Example: https://gobyexample.com/
* Learn Go with Tests: https://quii.gitbook.io/learn-go-with-tests
* More resources can be found [here](https://www.reddit.com/r/golang/comments/18ujt6g/new_at_go_start_here/)

**Spotify API**
* Reference the [Spotify API docs](https://developer.spotify.com/documentation/web-api) to get a sense of what we're able to do.
* Also, here's a [go library](https://github.com/zmb3/spotify) that makes working with the library easier. Feel free to browse it to see how specific Spotify functionality can be implemented in Go.

**Apple Music API**
* Similarly, here are the [Apple Music API docs](https://developer.apple.com/documentation/AppleMusicAPI) and a [go library](https://github.com/minchao/go-apple-music) that utilizes the API.

# Action Items
1. Share one thing you learned or find cool about Go in the comments below.
2. Set up a Spotify Developer account and [follow this tutorial](https://developer.spotify.com/documentation/web-api/tutorials/getting-started) to get info about one of your favorite artists. Post a screenshot of your API response below!

**Comment by adescoteaux1** [comment]
1. I find it interesting how minimalistic the syntax is in regards to things. Not sure I really like it but its cool
2. 
<img width="1092" alt="image" src="https://github.com/user-attachments/assets/97c235a3-19fd-4c82-b1c1-731ed05f49ee">

**Comment by aahiltn** [comment]
Cool thing about Go: 
Goroutines are cool! It makes sense for concurrent functions and multithreading to be a big part of a back-end language, and the addition of channels makes it look really powerful.


Info about Weston Estate: 
![image](https://github.com/user-attachments/assets/1f85da89-9b8c-4b01-893c-d1277fa1d9b8)

**Comment by zcroft27** [comment]
1. I particularly like Go's syntax for types--I like that return types and variable types are to the right of variables. I read the article on why they chose this, and they made interesting critiques about C. 
2. 
<img width="853" alt="image" src="https://github.com/user-attachments/assets/5ba191ca-faf5-4331-89b4-4094c4512123">
