### ISSUE TITLE
FE/BE: Onboarding/Login Finalized

### ISSUE THREAD

**Issue by gaikwadsid** [GenerateNU/platnm#114]
It is time to start finishing up these screens. The onboarding/login functionality has a solid foundation now to add the finishing touches.

Deliverables: 
Onboarding:
- Add the artist search screen
- add functionality to link Spotify to account
- add Spotify token to User Auth Table
- Add user to Supabase Auth Table as well as regular User Table
Login:
- Store Spotify token in context
- Store userId in context
Once Logged send user to Profile Page

CHECK-IN: Thursday, October 31st, push what you have to a branch on GitHub or slack a TL if you're stuck
DEADLINE: Monday, November 4nd, 11:59pm, be ready to merge

**Comment by ddusichka** [comment]
- add error handling
- look into expo redirect
