### ISSUE TITLE
Get reviews for a user

### ISSUE THREAD

**Issue by ddusichka** [GenerateNU/platnm#13]
Users should be able to get a list of their reviews of songs and albums by providing their userId to this endpoint.

Validate that the provided userId is valid. Ensure that the endpoint works even when the user has no reviews. This endpoint should also calculate their average numerical rating score. Sample endpoint response (a GetReviewsResponse object):
`
{
  avgRating: 7.3,
  reviews: [
review1, review2...
]
}`
Include tests!

**GET (/reviews/user/:userId)** returns a GetReviewsResponse

DELIVERABLES:

1 backend endpoints, GET reviews/user/:userId
Thorough testing - include Postman screenshots of successfully retrieved reviews and what happens when you provide an invalid userId

CHECK-IN: **Thursday, September 19th**, push what you have to a branch on GitHub
DEADLINE: **Monday, September 23rd**, 11:59pm, be ready to merge

**Comment by luisa-li** [comment]
Merged
