### ISSUE TITLE
Set Up Environment

### ISSUE THREAD

**Issue by gaikwadsid** [GenerateNU/platnm#7]
Follow the [Readme.md file](https://github.com/GenerateNU/platnm) to setup the environment for this project using Nix.

0. Clone the platnm repo, install nix if not done at orientation, and activate your devshell (`nix develop --impure`):
1. Make sure you're in the root repo. In your terminal, run `task backend:run`
2. Look for a "connected to database" message
3. Using your favorite API platform (Postman, your browser, etc.), hit http://localhost:8080/users and verify that you see a list of users being returned. If so, your backend is good to go!
4. **Comment a screenshot of your own successful API call below** :)

<img width="500" alt="image" src="https://github.com/user-attachments/assets/a6672a2e-69ad-48fb-b40f-4b98493679e9">

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/0e4f2aaa-2967-49cf-a868-86efd7154c6a">

**Comment by Alexcchip** [comment]
![image](https://github.com/user-attachments/assets/0ae06f3a-5c78-4545-b19b-0966f99f8693)
![image](https://github.com/user-attachments/assets/0ae06f3a-5c78-4545-b19b-0966f99f8693)
